---
- name: Add PPA for Mono
  apt_repository: repo=ppa:directhex/monoxide
 
- name: Update apt cache
  apt: update_cache=yes
 
- name: Install Mono
  apt: pkg=mono-complete
  # will fail installing monodoc-browser
  ignore_errors: true

- name: Import Mozilla LXR certificates into Mono
  command: mozroots --import --sync
  sudo: false

- name: Install nuget
  get_url: url=http://nuget.org/nuget.exe dest=/usr/local/bin/nuget.exe mode=0755

